project: artefacts/lite3-ros-demos
version: 0.1.0

jobs:
  test-rail-follow:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: mujoco
      
    scenarios:
      defaults:
        params:
          headless: "true"
          min_distance_to_travel: "7.5"
          mid360_mount_pitch: ["0.0", "29.0", "30.0"]
          mid360_mount_offset_x: "0.0"
      settings:
        - name: test_sim_rail_target_follow_distance
          run: "pixi run -e nav-test test-rail-follow"
  
  test-sim-sensors:
    type: test
    timeout: 5 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: mujoco
      
    scenarios:
      settings:
        - name: simulated_sensors_publishing_sensor_data
          run: "pixi run -e sim-test test-sim-sensors"
  
  test-rerun-recording:
    type: test
    timeout: 5 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: mujoco
      
    scenarios:
      defaults:
        params:
          headless: "true"
          min_distance_to_travel: "10.0"
      settings:
        - name: rerun_recording
          run: "pixi run -e nav-test test-rerun-recording"

  test-rerun-recording-m20:
    type: test
    timeout: 5 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: mujoco
      
    scenarios:
      defaults:
        params:
          headless: "true"
          min_distance_to_travel: "10.0"
      settings:
        - name: rerun_recording_m20
          run: "pixi run -e nav-test test-rerun-recording-m20"